interface RestErrorObject {
  httpStatus: number;
  message: string;
}

interface SystemcodeMapping {
  [systemcode: string]: RestErrorObject;
}
export abstract class ErrorCodes {
  static readonly SYSTEMCODEMAPPING: SystemcodeMapping = {
    1000: {httpStatus: 465, message: 'Please Enter Correct Compute Type'},
    1001: {httpStatus: 465, message: 'Please Enter Number of Periods'},
    1002: {httpStatus: 465, message: 'Please Enter Rate of Investment'},
    1003: {httpStatus: 465, message: 'Please Enter Payment Amount'},
    1004: {httpStatus: 465, message: 'Please Enter Future Value'},
    1005: {httpStatus: 465, message: 'Type can only have values 0 or 1'},
    1006: {httpStatus: 465, message: 'Request Could Not be Complete'},
    1007: {httpStatus: 465, message: 'Risk profile could not be updated!'},
    1008: {httpStatus: 465, message: 'Invalid export format!'},
    1009: {httpStatus: 465, message: 'Error occurred while exporting Investor Master'},
    1010: {httpStatus: 465, message: 'Error occured while sending Message Queue'},
    1011: {httpStatus: 465, message: 'Request Could Not Be Processed'},
    1012: {httpStatus: 465, message: 'Device not registered'},
    1013: {httpStatus: 465, message: 'Can not use a previously used mpin!'},
    1014: {httpStatus: 465, message: "Biometric couldn't be set on device"},
    1015: {httpStatus: 465, message: "Biometric couldn't be disabled"},
    1016: {httpStatus: 465, message: 'Max retry limit for OTP generation execced!. Kindly try after 12 hours!'},
    1017: {httpStatus: 465, message: 'Please retry after 1 minute!'},
    1018: {httpStatus: 465, message: 'Failed to publish OTP'},
    1019: {httpStatus: 465, message: 'Not able to update User Status'},
    1020: {httpStatus: 465, message: 'Please provide valid info!'},
    1021: {httpStatus: 465, message: 'Not able to update User Status'},
    1022: {httpStatus: 465, message: 'OTP is expired!'},
    1023: {httpStatus: 465, message: 'Invalid access token!'},
    1024: {httpStatus: 465, message: 'Invalid credentials!'},
    1025: {httpStatus: 465, message: 'Checksum invalid'},
    1026: {httpStatus: 465, message: 'File not uploaded'},
    1027: {httpStatus: 465, message: 'No files found'},
    1028: {httpStatus: 465, message: 'Authentication Failed'},
    1029: {httpStatus: 465, message: 'User id cannot be empty'},
    1030: {httpStatus: 465, message: 'No User found!'},
    1031: {httpStatus: 465, message: 'Process Failed'},
    1032: {httpStatus: 465, message: 'Professional Details required!'},
    1033: {httpStatus: 465, message: 'device not found'},
    1034: {httpStatus: 465, message: 'Device already exists'},
    1035: {
      httpStatus: 465,
      message: 'You are already logged in from devices. Please remove atleast one device from My Account section to continue'
    },
    1036: {httpStatus: 465, message: 'Error occured while binding your device!'},
    1037: {httpStatus: 465, message: 'Need to update the application'},
    1038: {httpStatus: 465, message: 'eKYC could not be completed'},
    1039: {httpStatus: 465, message: 'The request to join the family has been rejected/cancelled. You can resend the request after'},
    1040: {httpStatus: 465, message: 'Raise ticket. Multiple active mappings for this user-member'},
    1041: {httpStatus: 465, message: 'Request to member already sent earlier. Ask member to approve.'},
    1042: {httpStatus: 465, message: 'Member is already a member of user family.'},
    1043: {httpStatus: 465, message: 'We seem to have encountered a  temporary glitch. Kindly try after some time'},
    1044: {httpStatus: 465, message: 'We seem to have encountered a  temporary glitch. Kindly try after some time'},
    1045: {httpStatus: 465, message: 'Multiple Active Sessions. Refresh and try again'},
    1046: {httpStatus: 465, message: 'We seem to have encountered a  temporary glitch. Kindly try after some time'},
    1047: {httpStatus: 465, message: 'Total Amount cannot be negative'},
    1048: {httpStatus: 465, message: 'Cannot sell both Amount and Quantity'},
    1049: {httpStatus: 465, message: 'Unknown mode of Transaction'},
    1050: {httpStatus: 465, message: 'We seem to have encountered a  temporary glitch. Kindly try after some time'},
    1051: {httpStatus: 465, message: 'Please provide valid info!'},
    1052: {httpStatus: 465, message: 'Default Bank Account not found'},
    1053: {httpStatus: 465, message: 'You can only map less than or equal to available amount.'},
    1054: {httpStatus: 465, message: 'You can transfer entire amount or leave a minimum of'},
    1055: {httpStatus: 465, message: 'Price must be greater than zero.'},
    1056: {httpStatus: 465, message: 'Cannot generate CAS more than 2 times a day'},
    1057: {httpStatus: 465, message: 'Risk profile is not set for the account.'},
    1058: {httpStatus: 465, message: 'Please Enter Correct Objective Type'},
    1059: {httpStatus: 465, message: 'Please provide tenure in months.'},
    1060: {httpStatus: 465, message: 'Projection data not found.'},
    1061: {httpStatus: 465, message: 'Reverse Feed File Entry not created'},
    1062: {httpStatus: 465, message: 'Only active Systematic Plan can be updated!'},
    1063: {httpStatus: 465, message: 'On the day of Systematic plan can not be updated!'},
    1064: {httpStatus: 465, message: 'Systematic Method not found in current account!'},
    1065: {httpStatus: 465, message: 'Minimum 15days gap required between start date and first insatllment date!'},
    1066: {httpStatus: 465, message: 'nextExecutionDate can not be greater than end date!'},
    1067: {httpStatus: 465, message: 'Systematic Plan date is not in available dates for the instrument in systematic setting!'},
    1068: {httpStatus: 465, message: 'Invalid From Date'},
    1069: {httpStatus: 465, message: 'Invalid Type !'},
    1070: {httpStatus: 465, message: 'From Date cannot be greator than To Date !'},
    1071: {httpStatus: 465, message: 'Primary Holder not found'},
    1072: {httpStatus: 465, message: 'Interest Payment cannot be null'},
    1073: {httpStatus: 465, message: ''},
    1074: {httpStatus: 465, message: ''},
    1075: {httpStatus: 465, message: ''},
    1076: {httpStatus: 465, message: ''},
    1077: {httpStatus: 465, message: ''},
    1078: {httpStatus: 465, message: ''},
    1079: {httpStatus: 465, message: 'Customer Id Not found'},
    1080: {httpStatus: 465, message: 'Deposit Details not found'},
    1081: {httpStatus: 465, message: ''},
    1082: {httpStatus: 465, message: 'AccountId is required !'},
    1083: {httpStatus: 465, message: 'GoalCategories not found'},
    1084: {httpStatus: 465, message: 'Valid Type of Form Required!'},
    1085: {httpStatus: 465, message: 'Error occured while fetching GoalCategories!'},
    1086: {httpStatus: 465, message: 'Account not found'},
    1087: {httpStatus: 465, message: 'Holding Type Not Found'},
    1088: {httpStatus: 465, message: ''},
    1089: {httpStatus: 465, message: ''},
    1090: {httpStatus: 465, message: 'Nominee details required'},
    1091: {httpStatus: 465, message: ''},
    1092: {httpStatus: 465, message: 'InstrumentCategories not found'},
    1093: {httpStatus: 465, message: 'Error occured while fetching InstrumentCategories!'},
    1094: {httpStatus: 465, message: 'Nominee details can be set only once'},
    1095: {httpStatus: 465, message: ''},
    1096: {httpStatus: 465, message: 'Nominee not found!'},
    1097: {httpStatus: 465, message: 'Nominee id required to update!'},
    1098: {httpStatus: 465, message: 'Request Failes'},
    1099: {httpStatus: 465, message: 'Model definition not found'},
    1100: {httpStatus: 465, message: 'Some Error occurred'},
    1101: {httpStatus: 465, message: 'Please adjust the nominee percentage of other nominees before proceeding'},
    1102: {httpStatus: 465, message: 'Return Rate For The Risk Profile And Tenure not found'},
    1103: {httpStatus: 465, message: ''},
    1104: {httpStatus: 465, message: ''},
    1105: {httpStatus: 465, message: 'Occupation Not Found'},
    1106: {httpStatus: 465, message: 'BankAccount details not available!'},
    1107: {httpStatus: 465, message: 'riskProfileQuestions not found'},
    1108: {httpStatus: 465, message: 'Nominees are not found'},
    1109: {httpStatus: 465, message: ''},
    1110: {httpStatus: 465, message: 'Instrument not found'},
    1111: {httpStatus: 465, message: ''},
    1112: {httpStatus: 465, message: 'Error occured while fetching riskProfileQuestions!'},
    1113: {httpStatus: 465, message: 'riskProfiles not found'},
    1114: {httpStatus: 465, message: 'Invalid request body'},
    1115: {httpStatus: 465, message: 'Submit all answers for risk Profile'},
    1116: {httpStatus: 465, message: ''},
    1117: {httpStatus: 465, message: ''},
    1118: {httpStatus: 465, message: 'Error occured while fetching riskProfiles!'},
    1119: {httpStatus: 465, message: ''},
    1120: {httpStatus: 465, message: ''},
    1121: {httpStatus: 465, message: 'Mobile Number Missing'},
    1122: {httpStatus: 465, message: ''},
    1123: {httpStatus: 465, message: 'Wealth Source Type Not Found'},
    1124: {httpStatus: 465, message: 'Failed'},
    1125: {httpStatus: 465, message: 'Please provide customer ID'},
    1126: {httpStatus: 465, message: 'CartItem not found'},
    1127: {httpStatus: 465, message: ''},
    1128: {httpStatus: 465, message: ''},
    1129: {httpStatus: 465, message: "Refresh Token Expired'"},
    1130: {httpStatus: 465, message: 'toScheme (secondaryInstrumentId) missing for Switch/STP transaction'},
    1131: {httpStatus: 465, message: 'toScheme (secondaryInstrumentId) not found'},
    1132: {httpStatus: 465, message: 'Unknown error during cart item validation'},
    1133: {httpStatus: 465, message: 'Goal not found in RebalancingCheck during rebalancing cart process.'},
    1134: {httpStatus: 465, message: 'No Records Found'},
    1135: {httpStatus: 465, message: 'goalId must be present in all cart items'},
    1136: {httpStatus: 465, message: 'Invalid Instrument Id'},
    1137: {httpStatus: 465, message: 'Inactive Service Provider'},
    1138: {httpStatus: 465, message: ''},
    1139: {httpStatus: 465, message: 'Login attempts exceeded. User is now locked'},
    1140: {httpStatus: 465, message: 'Unclassified goal not found for the account.'},
    1141: {httpStatus: 465, message: 'Multiple unclassified goals found for the account.'},
    1142: {httpStatus: 465, message: 'Try again later'},
    1143: {httpStatus: 465, message: 'Could not fetch instruments for restricted schemes in specfic validation.'},
    1144: {httpStatus: 465, message: ''},
    1145: {httpStatus: 465, message: 'rtaId not found in master data for instrument:'},
    1146: {httpStatus: 465, message: 'Two Factor Auth Error !! Cannot Place Order'},
    1147: {httpStatus: 465, message: 'Secondary instrument missing for Switch transaction type.'},
    1148: {httpStatus: 465, message: 'Transaction Verification data not found!'},
    1149: {httpStatus: 465, message: ''},
    1150: {httpStatus: 465, message: ''},
    1151: {httpStatus: 465, message: 'User name required!'},
    1152: {httpStatus: 465, message: ''},
    1153: {httpStatus: 465, message: ''},
    1154: {httpStatus: 465, message: ''},
    1155: {httpStatus: 465, message: ''},
    1156: {httpStatus: 465, message: ''},
    1157: {httpStatus: 465, message: ''},
    1158: {httpStatus: 465, message: ''},
    1159: {httpStatus: 465, message: ''},
    1160: {httpStatus: 465, message: ''},
    1161: {httpStatus: 465, message: 'Some error occured getting response from external service'},
    1162: {httpStatus: 465, message: ''},
    1163: {httpStatus: 465, message: ''},
    1164: {httpStatus: 465, message: ''},
    1165: {httpStatus: 465, message: ''},
    1166: {httpStatus: 465, message: ''},
    1167: {httpStatus: 465, message: 'Address Details required'},
    1168: {httpStatus: 465, message: 'Correspondence address Line1 required!'},
    1169: {
      httpStatus: 465,
      message:
        "baseResponse['ns71:fetchTermDepositDetailsTermDepositInquiryResponse']['ns71:return']['responseservice:status']['responseservice:replyText']['_text']"
    },
    1170: {
      httpStatus: 465,
      message:
        "baseResponse['ns71:fetchTermDepositDetailsTermDepositInquiryResponse']['ns71:return']['responseservice:status']['responseservice:replyText']['_text']"
    },
    1171: {httpStatus: 465, message: 'MPIN is repetitive or in series, Set unique MPIN'},
    1172: {httpStatus: 465, message: ''},
    1173: {httpStatus: 465, message: ''},
    1174: {httpStatus: 465, message: 'Service Provider Account Not Found'},
    1175: {httpStatus: 465, message: ''},
    1176: {httpStatus: 465, message: 'Please wait for 24 hours to liquidate the RD after you invest in it.'},
    1177: {httpStatus: 465, message: 'Mpin is already setup'},
    1178: {httpStatus: 465, message: ''},
    1179: {httpStatus: 465, message: 'history Data not found'},
    1180: {httpStatus: 465, message: ''},
    1181: {httpStatus: 465, message: 'MPIN is repetitive or in series, Set unique MPIN'},
    1182: {
      httpStatus: 465,
      message:
        "baseResponse['ns10:liquidateFixedDepositResponse']['return']['responseservice:status']['responseservice:replyText']['_text']"
    },
    1183: {
      httpStatus: 465,
      message:
        "baseResponse['ns10:liquidateFixedDepositResponse']['return']['responseservice:status']['responseservice:replyText']['_text']"
    },
    1184: {httpStatus: 465, message: ''},
    1185: {httpStatus: 465, message: ''},
    1186: {httpStatus: 465, message: ''},
    1187: {httpStatus: 465, message: ''},
    1188: {httpStatus: 465, message: ''},
    1189: {httpStatus: 465, message: ''},
    1190: {httpStatus: 465, message: ''},
    1191: {
      httpStatus: 465,
      message:
        "baseResponse['ns10:liquidateRecurringDepositResponse']['return']['responseservice:status']['responseservice:replyText']['_text']"
    },
    1192: {httpStatus: 465, message: 'history Data not found'},
    1193: {httpStatus: 465, message: 'Please enter 10 digit mobile number'},
    1194: {httpStatus: 465, message: 'Please enter valid mobile number'},
    1195: {httpStatus: 465, message: 'Please enter valid mobile number'},
    1196: {httpStatus: 465, message: 'Please enter 10 digit mobile number'},
    1197: {
      httpStatus: 465,
      message: 'Oops!! Our system is temporarily down. We apologize for the inconvenience, please try after some time.'
    },
    1198: {httpStatus: 465, message: ''},
    1199: {httpStatus: 465, message: 'BosCode not found'},
    1200: {httpStatus: 465, message: ''},
    1201: {httpStatus: 465, message: 'Please try after some time'},
    1202: {httpStatus: 465, message: ''},
    1203: {httpStatus: 465, message: ''},
    1204: {
      httpStatus: 465,
      message:
        "baseResponse['ns10:verifyFixedDepositLiquidationResponse']['return']['responseservice:status']['responseservice:replyText']['_text']"
    },
    1205: {httpStatus: 465, message: ''},
    1206: {httpStatus: 465, message: ''},
    1207: {httpStatus: 465, message: ''},
    1208: {
      httpStatus: 465,
      message:
        "baseResponse['ns10:verifyFixedDepositLiquidationResponse']['return']['responseservice:status']['responseservice:replyText']['_text']"
    },
    1209: {
      httpStatus: 465,
      message:
        "baseResponse['ns10:verifyFixedDepositLiquidationResponse']['return']['responseservice:status']['responseservice:replyText']['_text']"
    },
    1210: {httpStatus: 465, message: 'No Records found in Idcom Details'},
    1211: {httpStatus: 465, message: 'Failure from IDCOM'},
    1212: {httpStatus: 465, message: 'Device id is required'},
    1213: {httpStatus: 465, message: 'Error while fetching callback status'},
    1214: {httpStatus: 465, message: 'Email id cannot be empty'},
    1215: {httpStatus: 465, message: 'Unable to update user details'},
    1216: {httpStatus: 465, message: 'Error occured while updating contact details.'},
    1217: {httpStatus: 465, message: 'User Details not found'},
    1218: {httpStatus: 465, message: 'The file format is invalid. Please upload the file in correct format.'},
    1219: {httpStatus: 465, message: 'Unable to update appUser'},
    1220: {httpStatus: 465, message: 'The file format is invalid. Please upload the correct CAMS File.'},
    1221: {httpStatus: 465, message: 'The file format is invalid. Please upload the correct KFintech File.'},
    1222: {
      httpStatus: 465,
      message: 'Your contact details(email & mobile number) for OTP authentication were not found. Please update the same with AMC'
    },
    1223: {httpStatus: 465, message: 'Update details in AMC'},
    1224: {
      httpStatus: 465,
      message:
        "baseResponse['ns10:verifyRecurringDepositLiquidationResponse']['return']['responseservice:status']['responseservice:replyText']['_text']"
    },
    1225: {httpStatus: 465, message: 'Error in External Api response'},
    1226: {httpStatus: 465, message: 'Could not find user details'},
    1227: {httpStatus: 465, message: 'Nominee Name required'},
    1228: {httpStatus: 465, message: 'Goals not found.'},
    1229: {httpStatus: 465, message: 'Required parameters missing.'},
    1230: {httpStatus: 465, message: 'Login attempts exceeded for a day. Please reset your PIN'},
    1231: {httpStatus: 465, message: 'SIP not found or inactive for the account.'},
    1232: {httpStatus: 465, message: 'Multiple SIPs found with same id. Some error.'},
    1233: {httpStatus: 465, message: 'Container name cannot be blank or empty!'},
    1234: {httpStatus: 465, message: 'No data found!'},
    1235: {httpStatus: 465, message: 'Amount Capping data not found'},
    1236: {httpStatus: 465, message: 'Model Portfolio not found'},
    1237: {httpStatus: 465, message: 'Model Portfolio instruments not found'},
    1238: {httpStatus: 465, message: 'Product not found'},
    1239: {httpStatus: 465, message: 'Error occured while Generating Files'},
    1240: {httpStatus: 465, message: 'Only parent app user must be present in appUserIds'},
    1241: {httpStatus: 465, message: 'isDefault property needs to be set to true'},
    1242: {httpStatus: 465, message: "Bank Account couldn't be found"},
    1243: {httpStatus: 465, message: 'Communication matrix not found'},
    1244: {httpStatus: 465, message: 'We seem to have encountered a  temporary glitch. Kindly try after some time'},
    1245: {httpStatus: 465, message: 'Some error occured fetching holding statement'},
    1246: {httpStatus: 465, message: 'Fund not found!'},
    1247: {httpStatus: 465, message: 'No transactions found for given pan!'},
    1248: {httpStatus: 465, message: 'Pan does not belong to this user'},
    1249: {httpStatus: 465, message: 'Email or Pan Card Number cannot be null'},
    1250: {httpStatus: 465, message: 'AccountId is missing.'},
    1251: {httpStatus: 465, message: 'Please provide at least SIP or Lumpsum amount.'},
    1252: {httpStatus: 465, message: 'Please provide risk profile.'},
    1253: {httpStatus: 465, message: 'The goal end date has already passed or is in the last month.'},
    1254: {httpStatus: 465, message: 'The goalId could not be found. Please provide correct goalId.'},
    1255: {httpStatus: 465, message: 'Model portfolios could not be processed.'},
    1256: {httpStatus: 465, message: 'fvLumpsum10k is null or undefined or zero'},
    1257: {httpStatus: 465, message: 'fvSIP1k is null or undefined or zero'},
    1258: {httpStatus: 465, message: 'Some error in calculating projections data.'},
    1259: {httpStatus: 465, message: 'Error occured while exporting Reverse Feed Reconcilliation Report'},
    1260: {httpStatus: 465, message: 'App File Entry not created'},
    1261: {httpStatus: 465, message: 'Error occured while exporting Rta Holding Reconcilliation Report'},
    1262: {httpStatus: 465, message: 'Rta Holding File Entry not created'},
    1263: {httpStatus: 465, message: 'Incorrect Status received!'},
    1264: {httpStatus: 465, message: 'On the day of Systematic plan can not be paused!'},
    1265: {httpStatus: 465, message: 'On the day of Systematic plan can not be stoped!'},
    1266: {httpStatus: 465, message: 'On the day of Systematic plan can not be activated!'},
    1301: {httpStatus: 465, message: 'device uniqueId is required'},
    1302: {httpStatus: 465, message: 'device not found'},
    1303: {httpStatus: 465, message: 'Error occured while updating device'},
    1304: {httpStatus: 465, message: 'Error occured while adding new device'},
    1305: {httpStatus: 465, message: 'Active version not found'},
    1306: {httpStatus: 465, message: 'Active App Version not found'},
    1307: {httpStatus: 465, message: 'Device unique id is missing from headers'},
    1308: {httpStatus: 465, message: 'Error occured while fetching Device Details!'},
    1309: {httpStatus: 465, message: 'Device does not exists'},
    1310: {httpStatus: 465, message: 'No families found for given userId.'},
    1311: {httpStatus: 465, message: 'No parents found for given userId.'},
    1312: {httpStatus: 465, message: 'No pending requests found for given userId.'},
    1313: {httpStatus: 465, message: 'Please provide child user Id.'},
    1314: {httpStatus: 465, message: 'Family for given parent and member not found.'},
    1315: {httpStatus: 465, message: 'Please provide parent user Id.'},
    1316: {httpStatus: 465, message: 'Please provide approval status.'},
    1317: {httpStatus: 465, message: 'Please provide member user code.'},
    1318: {httpStatus: 465, message: 'You can not add yourself as a member.'},
    1319: {httpStatus: 465, message: 'Parent user not found'},
    1320: {httpStatus: 465, message: 'Member not found'},
    1321: {httpStatus: 465, message: 'Email of member not found'},
    1322: {httpStatus: 465, message: 'Phone number and Country code of member not found'},
    1323: {httpStatus: 465, message: 'Environmnet variables not set'},
    1324: {httpStatus: 465, message: 'Nominee guardian not found'},
    1325: {httpStatus: 465, message: 'Please adjust the nominee percentage'},
    1326: {httpStatus: 465, message: 'Error While generating Document Nominee Files'},
    1327: {httpStatus: 465, message: 'Invalid Device Id'},
    1328: {httpStatus: 465, message: 'Both deviceId and uniqueId not found'},
    1329: {httpStatus: 465, message: 'Details is required!'},
    1330: {httpStatus: 465, message: 'Name is required!'},
    1331: {httpStatus: 465, message: 'Invalid Employee Code!'},
    1332: {httpStatus: 465, message: 'Invalid Date of Birth!'},
    1333: {httpStatus: 465, message: 'User already Exists'},
    1334: {httpStatus: 465, message: 'export format should be xlsx!'},
    1335: {httpStatus: 465, message: 'App Role ID Required!'},
    1336: {httpStatus: 465, message: 'Role not found!'},
    1337: {httpStatus: 465, message: 'App Role Mapping does not Exist!'},
    1338: {httpStatus: 465, message: 'Mapping not found!'},
    1339: {httpStatus: 465, message: "Couldn't identify maker"},
    1340: {httpStatus: 465, message: 'ROLE ID DOES NOT EXITS!'},
    1341: {httpStatus: 465, message: 'INVALID ROLE ID!'},
    1342: {httpStatus: 465, message: 'USERID DOES NOT EXISTS!'},
    1343: {httpStatus: 465, message: 'USERID ALREADY DISABLED!'},
    1344: {httpStatus: 465, message: 'USERID IS DELETED CANNOT BE MODIFIED!'},
    1345: {httpStatus: 465, message: 'USERID CAN ONLY BE EITHER ENABLED OR DELETED!'},
    1346: {httpStatus: 465, message: 'USERID ALREADY DELETED!'},
    1347: {httpStatus: 465, message: "USERID CAN'T BE DELETED!"},
    1348: {httpStatus: 465, message: 'USERID ALREADY LOCKED!'},
    1349: {httpStatus: 465, message: 'UAM USERID DOES NOT EXISTS!'},
    1350: {httpStatus: 465, message: 'INVALID EMAILID!'},
    1351: {httpStatus: 465, message: 'INVALID USER CODE!'},
    1352: {httpStatus: 465, message: 'INVALID USER TYPE!'},
    1353: {httpStatus: 465, message: 'INVALID CATEGORY!'},
    1354: {httpStatus: 465, message: 'INVALID USER NAME!'},
    1355: {httpStatus: 465, message: 'INVALID CONTACT NUMBER!'},
    1356: {httpStatus: 465, message: 'INVALID SALUTATION!'},
    1357: {httpStatus: 465, message: 'INVALID GENDER!'},
    1358: {httpStatus: 465, message: 'INVALID BRANCH CODE!'},
    1359: {httpStatus: 465, message: 'INVALID BRANCH NAME!'},
    1360: {httpStatus: 465, message: 'INVALID DEPARTMENT CODE!'},
    1361: {httpStatus: 465, message: 'INVALID DEPARTMENT NAME!!'},
    1362: {httpStatus: 465, message: 'INVALID ROLE'},
    1363: {httpStatus: 465, message: 'USERID/EMPCODE ALREADY EXISTS!'},
    1364: {httpStatus: 465, message: 'Error occured while exporting Admin Activity Report'},
    1365: {httpStatus: 465, message: 'Please provide atleast one config parameter'},
    1366: {httpStatus: 465, message: 'Mandate not found!'},
    1367: {httpStatus: 465, message: 'Token is required!'},
    1368: {httpStatus: 465, message: 'Accounts Details not found'},
    1369: {httpStatus: 465, message: 'App File not generated'},
    1370: {httpStatus: 465, message: 'Files not downloaded'},
    1371: {httpStatus: 465, message: 'AccountReferrals not found'},
    1372: {httpStatus: 465, message: 'Error occured while fetching Consolidated Documents!'},
    1373: {httpStatus: 465, message: 'Referral code already exists for this account!'},
    1374: {httpStatus: 465, message: 'Nominee address details not found'},
    1375: {httpStatus: 465, message: 'Guardian address details not found'},
    1376: {httpStatus: 465, message: 'Consent for deposit with nominee required'},
    1377: {httpStatus: 465, message: 'Nominee percentage can\t be more than 100%'},
    1378: {httpStatus: 465, message: 'Nominee details not found'},
    1379: {httpStatus: 465, message: 'User details not found'},
    1380: {httpStatus: 465, message: 'Investor nominee details not found'},
    1381: {httpStatus: 465, message: 'Incorrect onboarding step'},
    1382: {httpStatus: 465, message: "Can't select more than three nominees"},
    1383: {httpStatus: 465, message: 'Please adjust the nominee percentage'},
    1384: {httpStatus: 465, message: 'No nominees available to duplicate'},
    1385: {httpStatus: 465, message: 'Nominee investor detials not found'},
    1386: {httpStatus: 465, message: 'No nominee app user found'},
    1387: {httpStatus: 465, message: 'Address details not found'},
    1388: {httpStatus: 465, message: 'User not created successfully'},
    1389: {httpStatus: 465, message: "Dob should be less than today's date"},
    1390: {httpStatus: 465, message: "Nominee name shouldn't contains any special characters or numbers. Please update!!"},
    1391: {httpStatus: 465, message: "Guardian name shouldn't contains any special characters or numbers. Please update!!"},
    1392: {httpStatus: 465, message: "You can't create or update the nominee as mutual fund nominee"},
    1393: {httpStatus: 465, message: 'Nominee details are invalid'},
    1394: {httpStatus: 465, message: 'Spouse name is required'},
    1395: {httpStatus: 465, message: "You can't liquidate the tax saving fd within lock in period"},
    1396: {
      httpStatus: 465,
      message:
        'We regret to inform you that we are unable to proceed with your request, as your PAN and Aadhaar are not linked. To link your PAN with Aadhaar: https://eportal.incometax.gov.in/iec/foservices/#/pre-login/bl-link-aadhaar'
    },
    1397: {
      httpStatus: 465,
      message:
        "We regret to inform you that we are unable to proceed with your request, as your PAN and Aadhaar details couldn't be retrieved."
    },
    1398: {httpStatus: 465, message:  'PAN not found!'},
    1399: {httpStatus: 465, message:  'Invalid MPIN.'},
    1400: {httpStatus: 465, message: 'Consent for deposit is required'},
    1401: {httpStatus: 465, message: 'Please wait for 24 hours to liquidate the FD after you invest in it.'}
  };
}
